[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  NEXT_PUBLIC_SOCKET_URL = "https://vc-meet-server.up.railway.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_SOCKET_URL = "https://vc-meet-server.up.railway.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SOCKET_URL = "https://vc-meet-server.up.railway.app"
